// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmW6HgP1OZIDNDQpm7LtrrK2WX1ZTDKDE',
    appId: '1:309521282234:web:032824e0d6526592177e83',
    messagingSenderId: '309521282234',
    projectId: 'aqualert-af4f4',
    authDomain: 'aqualert-af4f4.firebaseapp.com',
    storageBucket: 'aqualert-af4f4.firebasestorage.app',
    measurementId: 'G-2JWB1GHDQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuD11JTjnmYKRpg41bZ42n95ii_i9o-p4',
    appId: '1:309521282234:android:d85aa75a6ad15bf6177e83',
    messagingSenderId: '309521282234',
    projectId: 'aqualert-af4f4',
    storageBucket: 'aqualert-af4f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpH1pvkmcLVdgHIH--8THPVIYXzsxd1nw',
    appId: '1:309521282234:ios:4beb84c0b51c5030177e83',
    messagingSenderId: '309521282234',
    projectId: 'aqualert-af4f4',
    storageBucket: 'aqualert-af4f4.firebasestorage.app',
    iosBundleId: 'com.example.aqualert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpH1pvkmcLVdgHIH--8THPVIYXzsxd1nw',
    appId: '1:309521282234:ios:4beb84c0b51c5030177e83',
    messagingSenderId: '309521282234',
    projectId: 'aqualert-af4f4',
    storageBucket: 'aqualert-af4f4.firebasestorage.app',
    iosBundleId: 'com.example.aqualert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmW6HgP1OZIDNDQpm7LtrrK2WX1ZTDKDE',
    appId: '1:309521282234:web:c22a812a4b4b5782177e83',
    messagingSenderId: '309521282234',
    projectId: 'aqualert-af4f4',
    authDomain: 'aqualert-af4f4.firebaseapp.com',
    storageBucket: 'aqualert-af4f4.firebasestorage.app',
    measurementId: 'G-H5NBJSDPWN',
  );
}
